import type { Metadata } from 'next'
import {ABeeZee} from 'next/font/google'
import './globals.css'
import { ThemeProvider, createGlobalStyle } from 'styled-components' 
import { StylesAndThemes } from './global.style'

const GlobalStyle = createGlobalStyle`
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html,
body {
  max-width: 100vw;
  overflow-x: hidden;
}
`

const abeezee = ABeeZee({weight:'400'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={abeezee.className}><ThemeProvider theme={StylesAndThemes}><GlobalStyle/>{children}</ThemeProvider></body>
    </html>
  )
}
